### ISSUE TITLE
how can i user this image

### ISSUE THREAD

**Issue by weironz** [4km3/docker-dnsmasq#35]
i'm new in dnsmasq,  i run 
```
docker run -d -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN 4km3/dnsmasq:2.85-r2
```
but i don't know what to do next, can you help ,thanks.

**Comment by panchoh** [comment]
你好 !

`docker-dnsmasq` is just a [minimal docker image](https://github.com/4km3/docker-dnsmasq/blob/master/Dockerfile) that runs `dnsmasq -k` (to keep it in the foreground), and will pass any extra arguments you supply in the command line invocation to that incantation, so you can make dnsmasq do whatever you want it to do.

For more info on what **dnsmasq** can do, you can start on the official [site](https://thekelleys.org.uk/dnsmasq/doc.html).

For starters, you could compose a suitable `dnsmasq.conf`, make it available to the container you run, and make use of it by supplying `--conf-file=/path/to/the/mapped/dnsmasq.conf`.

You can see that in action if you install **libvirt** in your system. It uses **dnsmasq** for providing DHCP and DNS to the virtual machines you create with it. You can simply do a `ps aux | grep dnsmasq` once **libvirt** is up and running, and you'll see the `--conf-file` argument to `dnsmasq` pointing to the actual path where the config file is.

On my system, the aforementioned config file it looks like this:

```
##WARNING:  THIS IS AN AUTO-GENERATED FILE. CHANGES TO IT ARE LIKELY TO BE
##OVERWRITTEN AND LOST.  Changes to this configuration should be made using:
##    virsh net-edit default
## or other application using the libvirt API.
##
## dnsmasq conf file created by libvirt
strict-order
pid-file=/run/libvirt/network/default.pid
except-interface=lo
bind-dynamic
interface=virbr0
dhcp-range=192.168.122.2,192.168.122.254,255.255.255.0
dhcp-no-override
dhcp-authoritative
dhcp-lease-max=253
dhcp-hostsfile=/var/lib/libvirt/dnsmasq/default.hostsfile
addn-hosts=/var/lib/libvirt/dnsmasq/default.addnhosts
```

You can find [here](https://fedoramagazine.org/dnsmasq-provide-dns-dhcp-services/) a way to leverage these features.

We'll try to add some pointers to this project's `README` so that this is no longer an issue. Thanks for reporting!

I will close the issue now. Feel free to reopen if you request more assistance.

Happy hacking!
